fdr_cutoff: 0.05
pvalue_cutoff: 0.01
maxSetSize: 500
cell_line: MV411
Conditions: MV411_CTRL,MV411_DRG
Imputation: F
SILAC: F
Species: Human
Samples: MV411_DRG
control: MV411_CTRL
CWD: /Users/Mahmoud.Hallal/Desktop/PhD/Generalized_pipeline
path_Input: /Users/Mahmoud.Hallal/Desktop/PhD/cell_lines_data/Stimulated_data/MV411_Midostaurin_03.2019/20190305_MHV4_TiO2_INC_MH/Phospho (STY)Sites.txt
Intensity_columns: ["Intensity.C1_INC1","Intensity.C1_INC2","Intensity.C2_INC1","Intensity.C2_INC2","Intensity.C3_INC1","Intensity.C3_INC2","Intensity.D1_INC1","Intensity.D1_INC2","Intensity.D2_INC1","Intensity.D2_INC2","Intensity.D3_INC1","Intensity.D3_INC2"]
Sum_conditions: T
Conditions_to_sum: [["Intensity.1_MV411_CTRL","Intensity.C1_INC1","Intensity.C1_INC2"],["Intensity.2_MV411_CTRL","Intensity.C2_INC1","Intensity.C2_INC2"],["Intensity.3_MV411_CTRL","Intensity.C3_INC1","Intensity.C3_INC2"],["Intensity.1_MV411_DRG","Intensity.D1_INC1","Intensity.D1_INC2"],["Intensity.2_MV411_DRG","Intensity.D2_INC1","Intensity.D2_INC2"],["Intensity.3_MV411_DRG","Intensity.D3_INC1","Intensity.D3_INC2"]]
Biological_replicates: 3-3
NWKIN_Input: /Users/Mahmoud.Hallal/Desktop/PhD/cell_lines_data/Stimulated_data/MV411_Midostaurin_03.2019/NetworKIN_onlineTool_output_cutoff0.75.csv
