channels:
- conda-forge
- bioconda
- r
- defaults
dependencies:
- r-essentials=3.6
- libopenblas=0.3.3
- bcftools
- bwa
- graphviz
- python
- samtools
- pyyaml
- pandas
- r-plyr
- r-dplyr
- r-xml
- r-ggplot2 
- r-reshape2
- r-gplots
- r-tidyr 
- r-robustbase
- r-liblinear
- r-ranger 
- r-pheatmap 
- r-venndiagram 
- r-filesstrings
- bioconductor-mzr
- bioconductor-msnbase
- r-rcpp
- r-rcppeigen 
- bioconductor-limma
- bioconductor-affy
- bioconductor-biobase
- bioconductor-annotationdbi
- bioconductor-genomicfeatures
- bioconductor-bsgenome
- bioconductor-bsgenome.hsapiens.ucsc.hg19
- bioconductor-homo.sapiens
- bioconductor-pathview
- r-shiny 
- r-imputelcmd
- r-yaml 
- bioconductor-topgo 
- r-igraph
